'use server'

import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'
import type { Assessment, Lead } from '@/lib/types'

const OLLAMA_HOST = process.env.OLLAMA_HOST ?? 'http://127.0.0.1:11434'
const MODEL = process.env.OLLAMA_MODEL ?? 'gemma3:4b'

// Genuinely generated by the local LLM from real lead + assessment data —
// not a template. Presentation only: the underlying verdict/score always
// comes from the deterministic rules engine, never from this text.
export async function generateCaseNarrative(leadId: string) {
  const supabase = await createClient()
  const { data: lead } = await supabase.from('leads').select('*').eq('id', leadId).single<Lead>()
  if (!lead) return { error: 'Lead not found.' }

  const { data: assessment } = await supabase
    .from('assessments').select('*, assessment_pillars(*)')
    .eq('lead_id', leadId).order('computed_at', { ascending: false }).limit(1)
    .maybeSingle<Assessment & { assessment_pillars: { pillar_code: string; score: number; band: string; headline: string }[] }>()

  const facts = [
    `Client: ${lead.client_name}, requesting ₹${lead.requested_amount} (${lead.loan_type}) over ${lead.tenure_years ?? 'unspecified'} years.`,
    lead.monthly_income ? `Monthly income: ₹${lead.monthly_income}.` : 'Monthly income not on file.',
    lead.cibil_score ? `CIBIL score: ${lead.cibil_score}.` : 'No bureau score on file.',
    lead.property_value ? `Property value: ₹${lead.property_value}, city: ${lead.property_city ?? 'unspecified'}.` : '',
    assessment ? `Assessment: composite score ${assessment.composite_score} (${assessment.composite_band}), verdict ${assessment.verdict}.` : 'No assessment run yet.',
    assessment?.assessment_pillars?.length
      ? `Pillars: ${assessment.assessment_pillars.map((p) => `${p.pillar_code} ${p.score} (${p.band}) — ${p.headline}`).join('; ')}.`
      : '',
  ].filter(Boolean).join('\n')

  const prompt = `Write a concise 2-3 sentence underwriting case summary for a loan partner reviewing this file. Plain factual tone, no markdown, no bullet points, third person. Only state facts given below — do not invent numbers.\n\n${facts}`

  let response: Response
  try {
    response = await fetch(`${OLLAMA_HOST}/api/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ model: MODEL, prompt, stream: false }),
    })
  } catch (err) {
    return { error: `Could not reach local model: ${(err as Error).message}` }
  }
  if (!response.ok) return { error: 'Local model unavailable.' }

  const body = await response.json() as { response: string }
  const narrative = body.response.trim()

  await supabase.from('leads').update({ case_narrative: narrative, case_narrative_generated_at: new Date().toISOString() }).eq('id', leadId)
  revalidatePath(`/partner/leads/${leadId}`)
  return { narrative }
}
